### ISSUE TITLE
call to undefined function

### ISSUE THREAD

**Issue by jonny-no1** [goalio/GoalioForgotPassword#2]
Click "request new password" ->

PHP Fatal error:  Call to undefined method GoalioForgotPassword\Mapper\Password::cleanPriorForgotRequests() in vendor/goalio/goalio-forgotpassword/src/GoalioForgotPassword/Service/Password.php on line 54

**Comment by yourithielen** [comment]
This is still broken. Will this be fixed?

**Comment by pdobrigkeit** [comment]
Hey, I am just looking at it right now. Just pushed a new commit that should contain the correct function. Once again, as I am not using the Zend\Db myself, you might please validate that the function works correctly ;)

**Comment by yourithielen** [comment]
It works, thanks a lot for the quick response!
