### ISSUE TITLE
Seriously, where are the tests?

### ISSUE THREAD

**Issue by ojhaujjwal** [goalio/GoalioForgotPassword#24]
Test is a must.

**Comment by pdobrigkeit** [comment]
You are more than welcome to submit a PR with tests.

**Comment by ojhaujjwal** [comment]
okay, i will think about it. I am a bit short of time at the moment.

**Comment by pdobrigkeit** [comment]
Well this is just one of maybe 50 modules of my application. I am also a bit short of time, that might be the reason there are no tests...
