### ISSUE TITLE
error message; goalio/goalio-forgotpassword 1.0.2 requires zf-commons/zfc-user 1.*

### ISSUE THREAD

**Issue by endyOfo** [goalio/GoalioForgotPassword#37]
hello
i tried using composer to upload the module but i get the following error message: 
  Problem 1
    - goalio/goalio-forgotpassword 1.0.2 requires zf-commons/zfc-user 1.\* -> no matching package found.
    - goalio/goalio-forgotpassword 1.0.1 requires zf-commons/zfc-user 1.\* -> no matching package found.
    - goalio/goalio-forgotpassword 1.0.0 requires zf-commons/zfc-user 1.\* -> no matching package found.
    - Installation request for goalio/goalio-forgotpassword 1.\* -> satisfiable by goalio/goalio-forgotpassword[1.0.0, 1.0.1, 1.0.2].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting

below is my json file; i did an update of the json file (prior to trying to download the package) and it worked fine.

"php": ">=5.3.3",
        "zendframework/zendframework": "2.3._",
        "zf-commons/zfc-user": "~0.1.2",
        "doctrine/doctrine-orm-module": "0._",
        "zf-commons/zfc-user-doctrine-orm": "0._",
        "zendframework/zend-developer-tools": "dev-master",
        "slm/mail": "~1.5",
        "bjyoungblood/bjy-authorize": "1.4._",
        "acelaya/zf2-acmailer": "4.*"

i would really appriciate any advice on how to download it.

warm regards

**Comment by AbdoSoufiane** [comment]
Hello !
 I am a beginner with ZF2 I tried to install goalio-forgotpassword but I've run into exactly that problem of andreea120.

Can you help me

Thank you very much!

**Comment by pdobrigkeit** [comment]
The problem lies in the line 

```
"zf-commons/zfc-user": "~0.1.2",
```

The `~0.1.2` says that you do not want to install zfc-user 1.x but only <1.0. Removing the ~ or requiring a newer version of zfc-user will fix that problem.
