### ISSUE TITLE
zfc-user

### ISSUE THREAD

**Issue by gp1** [goalio/GoalioForgotPassword#40]
I am using goalioforgotpassword, for forgot password functionality also I have zfc-user handling the users log-in and authentication stuffs. My problem is the zfc-user log-in view is being overridden by the zfc-user log-in template here in this module. Is there a way to configure so that i won't have this issue.

Thank You in Advance.

**Comment by pdobrigkeit** [comment]
I am not quite sure what you mean. But you can set the login template to anything you like using the `view_manager`config.

Take a look into the `config/module.config.php`

```
'view_manager' => array(
    'template_map' => array(
        'zfc-user/user/login' => __DIR__ . '/../view/zfc-user/user/login.phtml',
    ),
),
```

You can use that in any module that is loaded after GoalioForgotPassword and override the login template (or set it back to what it was before)

**Comment by gp1** [comment]
Thank you so much @pdobrigkeit. I was using template_path_stack before. Largely its due to my pretty less exposure on zf2. Closing the ticket :-)
