### ISSUE TITLE
Doctrine integration

### ISSUE THREAD

**Issue by bycosta** [goalio/GoalioForgotPassword#5]
It would be nice to have Doctrine integration, since ZfcUser has too.

**Comment by pdobrigkeit** [comment]
I will publish a seperate module for this. Currently the doctrine part is just in some other library that we are developing and I have to seperate it out.

**Comment by bgallagher** [comment]
Any more word on the your doctrine modules?

**Comment by pdobrigkeit** [comment]
Since the necessary PR to ZfcUser has been done, I will see if I find time to make the project ready this week.

**Comment by bramstroker** [comment]
This would be very nice, I'm using ZfcUser in combination with Doctrine now, but I cannot use the remember me functionality yet.

**Comment by bgallagher** [comment]
That'd be great. Let me know if I can help at all.

**Comment by pdobrigkeit** [comment]
Right now it is pretty much just taking out the doctrine mapper functionality which ended up in another module in our application, but that should be pretty straight forward. You guys can help just testing it out then ;)

**Comment by bgallagher** [comment]
Sign me up.

**Comment by pdobrigkeit** [comment]
Alright. Has not been tested yet, but as a preview:
https://github.com/goalio/GoalioForgotPasswordDoctrineORM

```
 "goalio/goalio-forgotpassword-doctrine-orm": "dev-master"
```

I close this issue. Please report any issues in the new repository ;)

**Comment by bgallagher** [comment]
Will try and get a chance to test it out in a day or two. Thanks.
