### ISSUE TITLE
Error on requesting a password reset of a non-existing email address

### ISSUE THREAD

**Issue by yourithielen** [goalio/GoalioForgotPassword#6]
The problem is in the forgotController on line 83. When a use doesn't exist the mapper returns false and on line 83 the is a check if the use is not null.

**Comment by acaciovilela** [comment]
@pdobrigkeit, @goalio, @stefankleff,  I have a PR to fix it.

**Comment by pdobrigkeit** [comment]
Thanks. Merged the PR, closing.
