### ISSUE TITLE
Composer.phar update issue

### ISSUE THREAD

**Issue by HurricaneHarry** [goalio/GoalioForgotPassword#7]
composer.json file:
        "zf-commons/zfc-base"               : "dev-master",
        "zf-commons/zfc-user"                : "dev-master",
        "goalio/goalio-forgotpassword"      : "dev-master",

$ php composer.phar update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for goalio/goalio-forgotpassword dev-master -> satisfiable by goalio/goalio-forgotpassword dev-master.
    - Conclusion: don't install zf-commons/zfc-base 0.0.1
    - Conclusion: remove zf-commons/zfc-base dev-master|install zf-commons/zfc-base 0.0.1
    - goalio/goalio-forgotpassword dev-master requires zf-commons/zfc-base 0.\* -> satisfiable by zf-commons/zfc-base 0.0.0, zf-commons/zfc-base 0.0.1, zf-commons/zfc-base 0.1.0.
    - Can only install one of: zf-commons/zfc-base dev-master, zf-commons/zfc-base 0.0.0.
    - Can only install one of: zf-commons/zfc-base dev-master, zf-commons/zfc-base 0.1.0.
    - Installation request for zf-commons/zfc-base dev-master -> satisfiable by zf-commons/zfc-base dev-master.

**Comment by HurricaneHarry** [comment]
I then chose to install the goalio mailservice first, then the forgotpassword service with composer.

This is what I get:
$ php composer.phar update goalio/goalio-forgotpassword
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: goalio/goalio-mailservice 0.1.0, goalio/goalio-mailservice dev-master.
    - Can only install one of: goalio/goalio-mailservice dev-master, goalio/goalio-mailservice 0.1.0.
    - goalio/goalio-forgotpassword dev-master requires goalio/goalio-mailservice 0.\* -> satisfiable by goalio/goalio-mailservice 0.1.0.
    - Installation request for goalio/goalio-forgotpassword dev-master -> satisfiable by goalio/goalio-forgotpassword dev-master.
    - Installation request for goalio/goalio-mailservice dev-master -> satisfiable by goalio/goalio-mailservice dev-master.

**Comment by pdobrigkeit** [comment]
Thanks for the report. Will look into it!

**Comment by pdobrigkeit** [comment]
My guess is, that with the new Tags which have been released on ZF-Commons, using dev-master das not work anymore...

I would recommend, that you change your composer.json to look like this:

```
"zf-commons/zfc-base" : "0.*",
"zf-commons/zfc-user" : "0.*",
"goalio/goalio-forgotpassword" : "0.*"
```

**Comment by HurricaneHarry** [comment]
This works, thank you.  I guess the tag system news would have reached me one way or another. :)
