### ISSUE TITLE
Can't override views .phtml

### ISSUE THREAD

**Issue by guimelon** [goalio/GoalioForgotPassword#8]
Hi,

I don't understand why but even with the appplication module after zfcuser and GoalioForgotPassword in the application.config.php, my login.phtml don't override the default in vendor.

**Comment by guimelon** [comment]
Ok I adjust my application module config with a new template_map

**Comment by gp1** [comment]
@GuillaumeM69 , Hi How did you adjust the application module? I could do that for just zfuser, but goalioforgotpassword has zfuser inside views, which is always executing first. Thank You in advance.
